version: "3.8"

services:
  web:
    # Use the image we built previously in TP-04
    image: counter-app:v1
    ports:
      - "${WEB_PORT}:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    restart: always
