# Highly secure, minimal attack surface base image
FROM alpine:3.18.4

# Upgrading system packages to their patched versions
RUN apk update && \
    apk upgrade && \
    apk add --no-cache curl

# Add a non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

CMD ["sh"]
