FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl=7.58.0-2ubuntu3 \
    libssl1.1=1.1.1-1ubuntu2.1~18.04.23 && \
    rm -rf /var/lib/apt/lists/*

CMD ["bash"]
